### ISSUE TITLE
Postcard wall images are too big

### ISSUE THREAD

**Issue by freekmurze** [spatie/spatie.be#53]
https://twitter.com/mrk_j/status/1278237320211283969

**Comment by willemvb** [comment]
Looks like all responsive images broke in a recent update, also those on the homepage and elsewhere.

If I understand correctly, the `getFirstMedia()` used for postcards should render the correct srcset:
https://docs.spatie.be/laravel-medialibrary/v8/responsive-images/getting-started-with-responsive-images/#displaying-responsive-images

The `srcset` attribute is empty however on all images, seems more like a backend issue?

**Comment by riasvdv** [comment]
For some reason the responsive image variants were gone, presumably because a `media-library:generate` was run as it seems the command doesn't generate the base responsive images.

I've regenerated them with a small script in Tinker, but this is something we should fix in the package https://github.com/spatie/laravel-medialibrary/issues/1949
